version: '3.8'

services:
  rtfrontend:
    build: ./rtfrontend
    env_file:
      - .env
    ports:
      - "3000:3000"

  processVideo:
    build: ./processVideo
    env_file:
      - .env
    ports:
      - "8080:8080"

  rtbackend:
    build: ./rtbackend
    env_file:
      - .env
    ports:
      - "5252:5252"
